# Generated by Django 2.2.6 on 2020-04-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_django_price_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='billing_email',
        ),
        migrations.AddField(
            model_name='payment',
            name='billing_phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
