# Generated by Django 2.2.6 on 2020-04-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subshop',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
