# Generated by Django 2.2.6 on 2020-04-20 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subshop', '0002_subshop_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subshop',
            options={'ordering': ('name',), 'permissions': (('manage_subshops', 'Manage_subshops'),)},
        ),
    ]
