# Generated by Django 2.2.6 on 2020-04-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0021_django_price_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='email',
        ),
        migrations.AddField(
            model_name='checkout',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
