# Generated by Django 2.2.6 on 2020-04-21 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_auto_20200421_0435'),
        ('subshop', '0003_auto_20200420_0336'),
        ('order', '0076_auto_20191018_0554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-pk',), 'permissions': (('manage_orders', 'Manage orders.'), ('assign_orders', 'Assign orders.'))},
        ),
        migrations.AddField(
            model_name='order',
            name='riderid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider', to='rider.Rider'),
        ),
        migrations.AddField(
            model_name='order',
            name='shopid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='subshop.SubShop'),
        ),
    ]
