# Generated by Django 2.2.6 on 2020-04-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0080_auto_20200428_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('unfulfilled', 'Unfulfilled'), ('assigned', 'Assigned'), ('partially fulfilled', 'Partially fulfilled'), ('fulfilled', 'Fulfilled'), ('canceled', 'Canceled'), ('rider accepted', 'rider accepted'), ('rider rejected', 'rider rejected')], default='unfulfilled', max_length=32),
        ),
    ]
