# Generated by Django 2.2.6 on 2020-06-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0081_auto_20200428_0512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-pk',), 'permissions': (('manage_orders', 'Manage orders.'), ('assign_order', 'Assign order.'))},
        ),
    ]
