# Generated by Django 2.2.6 on 2020-04-14 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subshop', '0002_subshop_created_at'),
        ('account', '0040_auto_20200407_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shopid',
            field=models.OneToOneField(blank=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_subshop', to='subshop.SubShop'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=False, max_length=12, unique=True),
        ),
    ]
