# Generated by Django 2.2.6 on 2020-04-20 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_auto_20200417_0431'),
        ('account', '0044_auto_20200416_0548'),
    ]

    operations = [
    ]
