# Generated by Django 2.2.6 on 2020-05-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_merge_20200420_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='channel',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
