# Generated by Django 2.2.6 on 2020-06-10 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_user_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='riderid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_rider', to='rider.Rider'),
        ),
    ]
