# Generated by Django 2.2.6 on 2020-04-16 10:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subshop', '0002_subshop_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_meta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('name', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('cnic', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('shopid', models.ForeignKey(blank=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_subshop', to='subshop.SubShop')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
