# Generated by Django 2.2.6 on 2020-04-21 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rider',
            options={'ordering': ('name',), 'permissions': (('manage_riders', 'Manage riders'),)},
        ),
    ]
