# Generated by Django 2.2.6 on 2020-04-29 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0003_auto_20200427_0044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rider',
            options={'ordering': ('id',), 'permissions': (('manage_riders', 'Manage riders'),)},
        ),
    ]
